# (c) Copyright IBM Corporation 2021
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- name: Define a new queue 
  hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment:
    _BPXK_AUTOCVT: "ON"
    ZOAU_HOME: "{{ ZOAU }}"
    PYTHONPATH: "{{ ZOAU }}/lib"
    LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
    PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin"
    _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
    _TAG_REDIR_ERR: "txt"
    _TAG_REDIR_IN: "txt"
    _TAG_REDIR_OUT: "txt"
    LANG: "C"

  tasks:
    - name: Define the queue
      zos_operator:
        cmd: "{{ mq_cpf }} DEF QLOCAL( {{ mq_queue_name }} ) DESCR(''A SIMPLE LOCAL QUEUE'')"
        verbose: false
      register: define_output

    - name: If define failed output readable failure information
      debug:
        msg: "{{ define_output.content }}"
      when: define_output.content is not search("CSQ9022I")

    - name: Check the define worked
      fail:
        msg: Define of queue failed 
      when: define_output.content is not search("CSQ9022I")

    - name: Issue display command
      zos_operator:
        cmd: "{{ mq_cpf }} DIS QLOCAL( {{ mq_queue_name }} )"
        verbose: false
      register: display_output

    - name: Output response from display command
      debug:
        msg: "{{ display_output.content }}"

    - name: Check the display worked
      fail:
        msg: Display of queue failed
      when: display_output.content is not search("CSQ9022I")