# (c) Copyright IBM Corporation 2021
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
- name: Display a queue
  hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"
  tasks:
    - name: Issue display command
      zos_operator:
        cmd: "ZMQ1 DIS QLOCAL( ZMQ1.DEAD.QUEUE )"
        verbose: false
      register: display_output
    - name: Output response from display command
      debug:
        msg: "{{ display_output.content[18].strip() }}"

    - block:
      - name: Fail if deadletter queue is not empty.
        fail: 
          msg: "Deadletter queue is not empty."
        when: display_output.content[18].strip() != "CURDEPTH(0)"

      rescue:
      - name: Send email to administrator to alert them of deadletter queue.
        tags: mail, email, e-mail
        mail:
          host: "{{ ansible_host }}"
          port: 25
          from: "{{ ansible_host }}"
          to: "{{ mail_to }}"
          subject: "Deadletter queue warning"
          body: |
            Non-empty deadletter queue on {{ inventory_hostname }}
        delegate_to: localhost
