---
#Install with 'ansible-galaxy install -r requirements.yml'
collections:
  - name: ibm.ibm_zos_core
    type: url
    source: "https://galaxy.ansible.com/download/ibm-ibm_zos_core-1.4.0-beta.1.tar.gz"
  - name: community.general
    type: url
    source: "https://galaxy.ansible.com/download/community-general-5.7.0.tar.gz"
